"""Embed the hydrologic arm graph in the engine (Clarity Fusion Stage 1).

The engine's runtime image carries only the binary (no SwiftPM resource
bundle), so the graph ships the way the lake directory does: one JSON string
literal, decoded at first use. With it goes a COARSE cell -> arm grid
(GRID_FACTOR x the Water Clarity frame, ~180 m on the ground: the majority arm
of each block's water, 0 = main stem, 255 = no water), run-length encoded as
LEB128 varint (value, run) pairs, base64 -- no zlib, which Foundation lacks on
Linux. The full-resolution grid stays in docs/data for the raster fusion.

usage: geo/bin/python embed_swift.py <final dir> <out .swift>
"""
import sys, os, json, base64, zlib
import numpy as np

FACTOR = 6


def varint(n):
    out = bytearray()
    while True:
        b = n & 0x7F; n >>= 7
        if n:
            out.append(b | 0x80)
        else:
            out.append(b); return bytes(out)


def rle(a):
    flat = a.ravel(); out = bytearray(); i = 0; n = flat.size
    while i < n:
        v = int(flat[i]); j = i
        while j < n and flat[j] == v:
            j += 1
        out += varint(v) + varint(j - i); i = j
    return base64.b64encode(bytes(out)).decode()


def main():
    final, out = sys.argv[1], sys.argv[2]
    graph = json.load(open(os.path.join(final, "guntersville.hydrology.json")))
    cells = json.load(open(os.path.join(final, "guntersville.arm_cells.json")))
    W, H = cells["width"], cells["height"]
    arm = np.frombuffer(zlib.decompress(base64.b64decode(cells["armGrid"])), np.uint8).reshape(H, W)
    raw = os.path.join(os.path.dirname(final), "out")
    water = np.load(os.path.join(raw, "water.npy"))
    h, w = (H + FACTOR - 1) // FACTOR, (W + FACTOR - 1) // FACTOR
    pad = lambda x, fill: np.pad(x, ((0, h * FACTOR - H), (0, w * FACTOR - W)), constant_values=fill)
    A = pad(arm, 0).reshape(h, FACTOR, w, FACTOR).transpose(0, 2, 1, 3).reshape(h, w, -1)
    Wm = pad(water, False).reshape(h, FACTOR, w, FACTOR).transpose(0, 2, 1, 3).reshape(h, w, -1)
    coarse = np.full((h, w), 255, np.uint8)
    for r in range(h):
        for c in range(w):
            vals = A[r, c][Wm[r, c]]
            if vals.size:
                coarse[r, c] = np.bincount(vals).argmax()
    grid = {"width": int(w), "height": int(h), "factor": FACTOR, "fullWidth": int(W), "fullHeight": int(H),
            "cornersLonLat": cells["cornersLonLat"],
            "cellMetresMercator": cells["cellMetresMercator"] * FACTOR, "arms": cells["arms"],
            "encoding": "LEB128 varint (value, run) pairs over uint8 row-major from the top row, base64; "
                        "0 = main stem, 255 = no water, k = arms[k]",
            "cells": rle(coarse)}
    payload = {"graph": graph, "grid": grid}
    js = json.dumps(payload, separators=(",", ":"), sort_keys=True)
    assert '"""#' not in js
    swift = f'''//
//  HydrologyData.swift
//  GENERATED by scripts/hydrology/embed_swift.py — do not edit by hand.
//
//  Lake Guntersville's hydrologic arm graph (Clarity Fusion Stage 1): every
//  tributary arm by water connectivity, its head and mouth, NHDPlus / NWM /
//  USGS identity, the main-stem regions from Nickajack to Guntersville Dam,
//  and a coarse cell -> arm grid. One JSON literal, decoded at first use
//  (a Swift literal of this size in initializer calls would not compile in
//  Cloud Build's 8 GB; see LakeDirectory.swift).
//

let hydrologyGuntersvilleJSON = #"""
{js}
"""#
'''
    open(out, "w").write(swift)
    print(f"wrote {out}: {len(js) / 1024:.0f} KB JSON; grid {w}x{h} ({len(grid['cells']) / 1024:.0f} KB rle)")


if __name__ == "__main__":
    main()
